### ISSUE TITLE
How do i find the requests in the Twitter DM developer page

### ISSUE THREAD

**Issue by sussron** [Mincka/DMArchiver#2]
Hi there! Thanks so much for replying to my message. I found my token ID using the developer tab in Chrome but how do i find the requests to get the DM Message ID once i've clicked on the conversation i'm looking at.  Do i do it the same way on same screen i found the token ID? Under elements?
Here is a screen shot of my window. I can switch to safari if that is easier to find it.
<img width="1093" alt="screenshot 2016-10-23 15 04 33" src="https://cloud.githubusercontent.com/assets/22826606/19628726/3d3513d0-9932-11e6-8591-6f400e659896.png">

Sorry to be such a novice, i really wish i understood all of this. So please excuse my ignorance, but i have a willingness and ability to take direction when it comes to tech stuff.

Thanks,
Ronnie
sussron1@netzero.com
Here is the developer tool in Safari but i'm not sure where to look for conversation iD for the conversation shown on screen as #TeamErin

<img width="1125" alt="screenshot 2016-10-23 15 27 20" src="https://cloud.githubusercontent.com/assets/22826606/19628850/41ad8ba6-9935-11e6-9de6-29f5157b5e64.png">

**Comment by sussron** [comment]
Now I can't find your reply to me with the updated information on how to do this. I'm new to this site. You had replied not to have me reply there but to click to fill out one of these, but now i can't get back to that initial interchange we had. I t hink i found the two ID#'s and now i don't know what to do. ugh.

**Comment by Mincka** [comment]
Hello!

You don't have to apologize, I'm here to help! 😄 

Actually, I've made the script a lot easier to use and you don't have to find your `auth_token` anymore. **It's also not mandatory anymore to find your conversation ID because the script will just get all of them**, which should be fine if you don't have hundred of conversations. :wink:

I've updated the documentation with the new installation and quick start steps.

I need you to tell me if you managed to perform the script installation on macOS. Try to open a Terminal and type the following:

```
$ pip3 install dmarchiver
$ dmarchiver
```

If you have an error with the first command, you may need to run the following to install Python 3:

```
$ brew install python3
```

If you've installed the script previously, run the following to upgrade it and run it:

```
$ pip3 install dmarchiver --upgrade
$ dmarchiver
```

The script will prompt you for your username & password and that's all you need now!

So I don't think you'll need your conversation ID but I guess that's the value of the `data-thread-id` in your second screenshot. In fact, the method I've previously given in the documentation was based on the identification in the conversation (or thread) ID using the "Network" tab to see the requests.

Just for you information, your first comment is right [there](https://github.com/Mincka/DMArchiver/commit/ac3b7dd556155d77c42b66f2773af8529a9697b5#commitcomment-19420643).

**Comment by sussron** [comment]
Omg so nice of you to reply!  I'll try what you suggest.  I had tried the
script thing and got error screen but I'll try again.  I will take photo of
screen if it gets error again.

Thanks again!!
Ronnie

**Comment by sussron** [comment]
Hi Julien I had replied but see message was kicked back because it exceed
size limitations.  I had attached screen shot of my errors.  I will try to
reduce file size and resend.

**Comment by Mincka** [comment]
Maybe you could copy and paste the text of the error?

Could your error be related to this one? #1

**Comment by sussron** [comment]
Error

**Comment by Mincka** [comment]
Sorry, but it seems the images are not added to the thread when they are embedded in e-mail.

Could you just copy and paste the error here? Thanks.

**Comment by sussron** [comment]
I attached the image/screenshot here ad a *.png image on phone using
Gmail.  I can post it on your site tomorrow.
Sorry

**Comment by Mincka** [comment]
Hello,

The instructions for Mac OS X and the tool have been updated with bug fixes. Could you follow the updated instructions on the homepage and tell me if you manage to download your DMs?

**Comment by Mincka** [comment]
An easier method is now available to retrieve a conversation ID:
https://github.com/Mincka/DMArchiver#how-to-get-a-conversation_id
