### ISSUE TITLE
it doesn't download images, even with -di -dg command

### ISSUE THREAD

**Issue by adibatawfeek** [Mincka/DMArchiver#30]
i am not able to download images

**Comment by Mincka** [comment]
Hello,

Please provide a screenshot of the tool execution and the operating system used.

**Comment by Jonny456** [comment]
HI I'm using windows. How do I get it to download images etc?
I run the program through from a folder within my E drive
![capture](https://user-images.githubusercontent.com/31113473/29435128-ac6a72a8-839d-11e7-97e8-08c194e68fdf.JPG)
What should I do to use the commands. Sorry to be so basic. I know bugger all about programming but I love your tool

**Comment by Jonny456** [comment]
I'm using windows and don't know how to run the command that will capture the images coz I know little about coding. Can you advise me? Sorry to be so basic. Love the tool otherwise. THANK YOU.
![capture](https://user-images.githubusercontent.com/31113473/29435313-7477f158-839e-11e7-9b90-fb47ed85e9a8.JPG)

**Comment by Mincka** [comment]
@Jonny456 Follow these instructions:
1. Use Windows + R shortcut
2. Type "cmd", enter
3. Type "E:", enter
4. Type "cd Dropbox\...\...\" (replace with the path where is DMArchiver.exe), enter
5. Type "dmarchiver -di -dg -dv", enter

**Comment by Jonny456** [comment]
Thank you so much. Even a programming novice can follow this!
