### ISSUE TITLE
KeyError: 'trusted'

### ISSUE THREAD

**Issue by GTXSam** [Mincka/DMArchiver#35]
Conversation ID not specified. Retrieving all the threads.
Traceback (most recent call last):
  File "dmarchiver\cmdline.py", line 107, in <module>
  File "dmarchiver\cmdline.py", line 96, in main
  File "dmarchiver\core.py", line 302, in get_threads
KeyError: 'trusted'
Failed to execute script cmdline

**Comment by Mincka** [comment]
Seems related to #29. Can you try with the previous release (0.1.7)?

**Comment by brandonnn** [comment]
Just to weigh in, I'm getting this on Win/Mac, on both 0.1.7 and 0.1.8!

**Comment by Mincka** [comment]
Did the tool worked previously or it is the first time you use DMArchiver?

**Comment by brandonnn** [comment]
Wednesday was the first time I'd tried! I disabled 2FA for a bit first, tried with both username & email addy as the login, tried generating a temporary app password instead of my main Twitter password, all ended in KeyError on both versions!

**Comment by Mincka** [comment]
Ok. Since I am not able to reproduce the error condition. I would need to confirm if the issue is related to the script behavior or your account itself.

In your browser, when you click on "Messages" and the pop-up is displayed, a request is made to https://twitter.com/messages. The script is looking for the content of an array, which is [inner][trusted].

I need to check if this array is present in the response. Could you check in your browser for the response content for this request? 

You will find below the screenshots of the developper console (F12) in Firefox and Chrome:

![image](https://user-images.githubusercontent.com/6184289/31033250-a0aaf080-a55f-11e7-980a-fd935925673c.png)

![image](https://user-images.githubusercontent.com/6184289/31033426-4811cac4-a560-11e7-914a-c0aa15f82a4f.png)

**Comment by brandonnn** [comment]
I get identical results in both Chrome and Firefox, frustratingly, yeah!

![screen shot 2017-09-29 at 3 10 04 pm](https://user-images.githubusercontent.com/624235/31034159-75e19052-a528-11e7-8b90-270c86f265a9.png)

**Comment by brandonnn** [comment]
(side note: I get that suspicious connection email every single time I run this, just in case that means it could potentially be blocking the view)

**Comment by Mincka** [comment]
Thanks. Since you tried on Win and macOS, this may be not related to the user-agent either (Firefox on Windows).

Do you use a compiled binaries in the releases? Would it be ok for you to test with a custom build (on Windows preferably), that will extract the raw content of the HTTP responses? I support this for the tweet content with -raw but not the retrieval of conversation list currently.

I also  have the e-mail alert from Twitter each time I run the script.

**Comment by brandonnn** [comment]
Yeah, I just followed you on Twitter if you want to DM me a custom build!

**Comment by Mincka** [comment]
Could you both try with the latest release (0.1.9)?

If the issue is still there, I will need the output of the "conversation-list.txt" when script is run with the "-r" parameter. @brandonnn : you can give me content over DM on Twitter. Thanks!

**Comment by Mincka** [comment]
@Auroratic : Can you test with the latest release? It is now working for @brandonnn
