### ISSUE TITLE
Error when using the lastest release -  not all messages downloaded

### ISSUE THREAD

**Issue by sussron** [Mincka/DMArchiver#38]
Hi there.
I downloaded the latest Mac release. When I ran the archiver, I noticed it only went back to July 2017 in some of the threads and not all the way to the beginning.  One of my largest DM messages is about 22MB txt file once downloaded and this time it was only 1.5MB.  I did one screen shot of what seems to be different than what I normally see.  Hope this helps in the explanation
As a reminder I'm using the Mac version.

Thanks 
Ronnie
<img width="667" alt="screenshot 2017-10-06 19 25 34" src="https://user-images.githubusercontent.com/22826606/31302489-21a9df1e-aad0-11e7-80e8-f45f8976a917.png">
<img width="843" alt="screenshot 2017-10-06 19 56 01" src="https://user-images.githubusercontent.com/22826606/31302525-66ea458c-aad0-11e7-81e9-da2a37487782.png">
<img width="816" alt="screenshot 2017-10-06 19 55 37" src="https://user-images.githubusercontent.com/22826606/31302524-66e8b32a-aad0-11e7-94cf-c977bed15a90.png">

**Comment by sussron** [comment]
The main one that i am concerned about, conversation 629006352329760768  had 
This month:
Starting crawl of '629006352329760768'
Previous conversation not found. Creating a new one with incremental support.
Begin of thread reached
Total processed tweets: 13259
Writing conversation to /Users/ronniesussman/Downloads/629006352329760768.txt

But in the prior one I ran in February it had 166,858 tweets.


![image](https://user-images.githubusercontent.com/22826606/31302666-964d0a02-aad1-11e7-8b6d-8a397a7312cc.png)

**Comment by Mincka** [comment]
Hello Ronnie,

I tried to run the script on my conversations without issues, even if my biggest conversations has "only" 22144 tweets. Sometimes, due to a connection error, the script may think it has reached the end of the thread and will continue with the next one. The only thing you can try here is to run the script again.

However, I think you miss something important. The script now allows you to perform incremental updates. That means only the new messages are downloaded and added to your archive. You just have to run the script where your log files are.

To know if a conversation file can be automatically completed, you just have to look if the last line contains `[LatestTweetID] XXXXXXXXXXXX`. It is an indication for the script to know how many new tweets have been sent since the last run.

If you did not keep a complete version of `629006352329760768`, I suggest that you delete the incomplete file you just downloaded and start again. If this time, all the messages are downloaded, continue the next time to run the script with the complete file, in the same folder. The script will just add the new tweets and your backup will be done a lot faster. 😃

**Comment by sussron** [comment]
Oh i had missed that Julien, what a great new feature.   I have kept my updates in separate folders so that is probably why it may have known it was run but i didn't get all the information in the download folder where the downloads automatically go.

<img width="1014" alt="screenshot 2017-10-07 09 11 13" src="https://user-images.githubusercontent.com/22826606/31308155-82a1eacc-ab3f-11e7-8c54-3818dcb77409.png">

**Comment by sussron** [comment]
Now this is strange so i ran the command but got this note:
Ronnies-MacBook-Pro:downloads ronniesussman$ ./dmarchiver -id "629006352329760768" -di -dg
DMArchiver 0.2.0
Running on Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 19 2015, 20:38:52) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Enter your username or email: beckybulldognj
Enter your password (characters will not be displayed): 
Authentication succeedeed.

Press Ctrl+C at anytime to write the current conversation and skip to the next one.
 Keep it pressed to exit the script.

Conversation ID specified (629006352329760768). Retrieving only one thread.
Starting crawl of '629006352329760768'
Previous conversation not found. Creating a new one with incremental support.
Begin of thread reached
Total processed tweets: 0
Writing conversation to /Users/ronniesussman/Downloads/629006352329760768.txt
Ronnies-MacBook-Pro:downloads ronniesussman$

**Comment by sussron** [comment]
I do see that in the file I downloaded in June that the last tweet was 6/27/17 and in this one i ran yesterday it started incrementally with 7/27/17 so it missed a month of messages but created a txt with everything since 7/27/17. I attempted this morning to run a clean one of that particular conversation and moved all the prior txt log files into a separate folder from downloads so that it would be fresh but it downloaded nothing.  I'm afraid to delete the txt i have moved to this alternate location, but is the script somehow finding it on my computer and therefore deeming that zero new messages have been found?

Ronnie

Thanks and sorry for my ignorance. I love that you have created this amazing tool.

**Comment by sussron** [comment]
I will try running again as you suggested and let you know.  Thanks again.

**Comment by sussron** [comment]
Hi Julien,
Here's an update. i ran it and this time it came up with the 220,000+ tweets and created folders for the images, videos etc.

Thank you!

**Comment by Mincka** [comment]
Hi Ronnie,

Good to know it finally worked properly. 220,000 is insane. 😄 

Keep it up with the incremental updates. 😉 

Julien
